#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ruby_build',
  :git => 'git://github.com/fnichol/chef-ruby_build.git', 
  :ref => 'v0.6.0'
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git', 
cookbook 'apt',
  :git => 'git://github.com/fnichol/chef-apt.git'
cookbook 'redis',
  :git => 'git://github.com/fnichol/chef-redis.git'
cookbook 'nodejs',
  :git => 'https://github.com/fnichol/nodejs-cookbook'
cookbook 'git',
  :git => 'git://github.com/fnichol/chef-git.git'
