#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ruby_build',
  :git => 'git://github.com/fnichol/chef-ruby_build.git', 
  :ref => 'v0.6.0'
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git'
cookbook 'apt',
  :git => 'git://github.com/fnichol/chef-apt.git'
cookbook 'redis',
  :git => 'git://github.com/fnichol/chef-redis.git'
cookbook 'nodejs',
  :git => 'git://github.com/fnichol/nodejs-cookbook.git'
cookbook 'git',
  :git => 'git://github.com/fnichol/chef-git.git'
cookbook 'rails-lastmile',
  :path => 'vendor/rails-lastmile'
cookbook 'redisio',
  :git => 'git://github.com/brianbianco/redisio.git'
cookbook 'mongodb',
  :git => 'git://github.com/edelight/chef-cookbooks.git'
cookbook 'imagemagick',
  :git => 'git://github.com/opscode-cookbooks/imagemagick.git'
cookbook 'vim',
  :git => 'git://github.com/opscode-cookbooks/vim.git'
cookbook 'postgresql',
  :git => 'vendor/postgresql'
